
"echo Run the web server in a separate terminal: 'cd ~/rustprojects/varweeks_millis_clock/web_server_folder/;basic-http-server'",
"echo Run the web app in your browser: 'http://127.0.0.1:4000/varweeks_millis_clock/'",
"echo    $ cargo make doc - includes from Cargo.toml to README.md and from README.md to main.rs or lib.rs, generates doc and copies to docs folder, exports codetour to .md.",
"echo    $ cargo make publish_to_web - automation for publish",
"echo "
]

	

[tasks.publish_to_web]
description = "publish to web server"
workspace = false
clear = true
# backslash is the escape character for all other special characters.
# and then another time I have to escape the backslash. So 4 backslash for one backslash.
script = [
    "echo ",
    "echo $ git tag -f -a v${CARGO_MAKE_CRATE_VERSION} -m version_${CARGO_MAKE_CRATE_VERSION}",
    "git tag -f -a v${CARGO_MAKE_CRATE_VERSION} -m version_${CARGO_MAKE_CRATE_VERSION}",
    "echo $ rsync -a --info=progress2 --delete-after ~/rustprojects/varweeks_millis_clock/web_server_folder/varweeks_millis_clock/ ~/rustprojects/googlecloud/var/www/bestia.dev/varweeks_millis_clock/",
    "rsync -a --info=progress2 --delete-after ~/rustprojects/varweeks_millis_clock/web_server_folder/varweeks_millis_clock/ ~/rustprojects/googlecloud/var/www/bestia.dev/varweeks_millis_clock/",
    "echo $ rsync -e ssh -a --info=progress2 --delete-after ~/rustprojects/googlecloud/var/www/bestia.dev/varweeks_millis_clock/ luciano_bestia@bestia.dev:/var/www/bestia.dev/varweeks_millis_clock/",
    "rsync -e ssh -a --info=progress2 --delete-after ~/rustprojects/googlecloud/var/www/bestia.dev/varweeks_millis_clock/ luciano_bestia@bestia.dev:/var/www/bestia.dev/varweeks_millis_clock/",
]