name: RustAction

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt_build_test:

    runs-on: ubuntu-latest

    steps:
    - uses: jetli/wasm-pack-action@v0.3.0
      with:
        version: 'latest'
    - uses: actions/checkout@v2
    - name: Fmt
      run: cargo fmt -- --check
    - name: Build
      run: wasm-pack build --target web --release
